# 📚 Introduction to Common Machine Learning Libraries

In this notebook, we will explore four important libraries for Machine Learning and Deep Learning:
- **scikit-learn**: for classical Machine Learning models
- **PyTorch**: flexible Deep Learning
- **TensorFlow/Keras**: scalable Deep Learning
- **HuggingFace Transformers**: powerful Natural Language Processing

---
## 🛠 1. Installation Instructions

Before we start, install the required libraries:

```bash
pip install scikit-learn torch tensorflow tf-keras transformers


# 2. scikit-learn - Classical Machine Learning
scikit-learn provides simple, efficient tools for traditional machine learning tasks like classification, regression, clustering.

### Example: SVM on Iris Dataset

In [4]:
# Import and train a simple SVM on Iris dataset
from sklearn import datasets, svm
X, y = datasets.load_iris(return_X_y=True)
clf = svm.SVC()
clf.fit(X, y)
print("SVM Predictions on first 5 samples:", clf.predict(X[:5]))

SVM Predictions on first 5 samples: [0 0 0 0 0]


### k-Nearest Neighbors on Digits Dataset
k-Nearest Neighbors is a lazy learning algorithm — it memorizes training data.

In [5]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

digits = load_digits()
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, random_state=42)
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
print(f"kNN Accuracy: {knn.score(X_test, y_test):.2f}")

kNN Accuracy: 0.99


## 3. PyTorch - Flexible Deep Learning
PyTorch is a deep learning framework that gives maximum flexibility with dynamic graphs.
### Example: Simple Neural Network

In [6]:
import torch
import torch.nn as nn

model = nn.Sequential(
    nn.Linear(4, 3),
    nn.ReLU(),
    nn.Linear(3, 3)
)

sample_input = torch.rand(5, 4)
output = model(sample_input)
print("PyTorch Model Output:\n", output)

PyTorch Model Output:
 tensor([[-0.1356,  0.1780, -0.4705],
        [-0.0771,  0.1521, -0.4137],
        [ 0.0413,  0.0998, -0.2990],
        [ 0.1134,  0.0679, -0.2290],
        [ 0.0213,  0.1086, -0.3183]], grad_fn=<AddmmBackward0>)


## 4. TensorFlow/Keras - High Level Deep Learning
TensorFlow with Keras API allows quick and easy model building for production.
### Example: Same Neural Network

In [7]:
from tensorflow import keras

keras_model = keras.Sequential([
    keras.layers.Dense(3, input_shape=(4,), activation='relu'),
    keras.layers.Dense(3)
])

keras_output = keras_model(keras.backend.random_uniform((5, 4)))
print("Keras Model Output:\n", keras_output)

Keras Model Output:
 tf.Tensor(
[[-0.09862874  0.04957953 -0.09598392]
 [-0.60820967  0.15008797 -0.6064325 ]
 [-0.25682634  0.06337707 -0.25607592]
 [-0.6959785   0.1717467  -0.6939449 ]
 [-0.51550037  0.1272101  -0.5139941 ]], shape=(5, 3), dtype=float32)


/opt/anaconda3/envs/batey/lib/python3.9/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


## 5. HuggingFace Transformers - Pretrained NLP Models
HuggingFace provides access to thousands of powerful pretrained models for text, vision, and more.
### Example: Sentiment Analysis

In [8]:
from transformers import pipeline

classifier = pipeline('sentiment-analysis')
result = classifier("I love studying Machine Learning!")
print("Sentiment Analysis Result:", result)

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use mps:0


Sentiment Analysis Result: [{'label': 'POSITIVE', 'score': 0.9995645880699158}]
